services:
  - type: web
    name: short-it
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        placeholder: "Enter Neon PostgreSQL Connection string"
      - key: UPSTASH_REDIS_REST_URL
        placeholder: "Enter Upstash Redis REST URL"
      - key: UPSTASH_REDIS_REST_TOKEN
        placeholder: "Enter Upstash Redis REST Token"
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: "https://ddu-projects.com"
      - key: ADMIN_EMAIL
        value: "vatsal.chandrani.11@gmail.com"
      - key: ADMIN_PASSWORD
        value: "vats@l1118"
      - key: BREVO_API_KEY
        placeholder: "Enter Brevo API Key"
      - key: EMAIL_FROM
        value: "shortit.team@gmail.com"
      - key: GMAIL_USER
        value: "shortit.team@gmail.com"
      - key: GMAIL_PASS
        placeholder: "Enter Gmail App password (fallback)"
